### ISSUE TITLE
Issue with props being passed down by renderItem function

### ISSUE THREAD

**Issue by ndford2015** [coderiety/react-list#200]
```
class TabFeed extends React.Component {

  state = {
    tabs: []
  }

  componentWillMount() {
    fetch('/api/tabs').then((tabs) => {
      return tabs.json();
    }).then((tabs) => {
      this.setState({tabs: tabs});
    })
  }

  renderItem = (index, key) => {
    return <Tab
      key={key}
      index = {index}
      {...this.state.tabs[index]}/>
  }

  render() {
    return (
      <div>
        <ReactList
          itemRenderer ={this.renderItem}
          length={this.state.tabs.length}
          type='variable' />
      </div>
    )
  }
}

module.exports = TabFeed;
```

The list I am rendering contains 7 items. It seems like every time I scroll down, react-list is rendering the first 2-3 items (indices 0-2), rather than indices 3-6. See gif below (watch how the titles and contents of inner divs change):

![props_issue](https://user-images.githubusercontent.com/22919023/34387496-7c7d85c8-eafc-11e7-8402-a824fa71e7bd.gif)

It seems as though the props being passed down by this.state.tabs are being updated based on the key value rather than index value for some reason. Please let me know if you need any additional info. Any help is greatly appreciated!

**Comment by jasondecastro** [comment]
Having this same exact issue. Were you able to get this resolved? @ndford2015

**Comment by jasondecastro** [comment]
@ndford2015 @caseywebdev Also, this issue doesn't happen on `simple`, only on `variable` or `uniform`.

**Comment by ndford2015** [comment]
@jasondecastro Seems like it was an issue with keys not being unique. I decided to create my own unique keys (e.g a simple counter), and it fixed the issue.
