### ISSUE TITLE
getVisibleRange not firing on horizontal list

### ISSUE THREAD

**Issue by jerninvien** [coderiety/react-list#222]
Can anyone help me get this method to fire please on a horizontal infinite scrolling list? None of these methods are currently firing (getVisibleRange(), scrollAround() and scrollTo()). Here is my code thus far:

```
_getVisibleRange = (a, b) => {
		console.log('getVisibleRange', a, b);
	}

	_scrollAround = (index) => {
		console.log('_scrollAround', index);
	}

	_scrollTo = (index) => {
		console.log('_scrollTo', index);
	}

	_renderItem = (index) => {
		const { loading, loadMoreItems, list } = this.props;
		if (!loading && (list.length - index < 10)) {
			loadMoreItems();
		}

		return <div className="cardWrapper" key={index}>{this.props.list[index]}</div>;
	}

	_onScroll = (e) => {
		console.log('_onScroll', e);
	}


	render() {
		const {
			initialIndex,
			list,
			pageSize,
			threshold,
			type,
			useStaticSize,
			useTranslate3d,
		} = this.props;

		return (
			<ReactList
				axis="x"
				getVisibleRange={this._getVisibleRange}
				initialIndex={initialIndex}
				itemRenderer={this._renderItem}
				length={list.length}
				pageSize={pageSize}
				scrollAround={this._scrollAround}
				scrollTo={this._scrollTo}
				threshold={threshold}
				type={type}
				useStaticSize={useStaticSize}
				useTranslate3d={useTranslate3d}
			/>
		);
	}
```

**Comment by caseywebdev** [comment]
Those aren't props, they're [methods on the component](https://github.com/coderiety/react-list#methods). For example if `list` is a reference to your rendered list component, you can use `list.scrollTo(5)` to scroll to index 5.

**Comment by jerninvien** [comment]
> Those aren't props, they're [methods on the component](https://github.com/coderiety/react-list#methods). For example if `list` is a reference to your rendered list component, you can use `list.scrollTo(5)` to scroll to index 5.


Thanks using refs i got` getVisibleRange()` to fire (e.g. in componentDidUpdate), however it still returns `[undefined, undefined]`. Any tips? Perhaps it doesn't work for horizontal lists? My list currently scrolls perfectly, caches content and I got it to do infinite scrolling via async loading, all rather impressive from this package.

**Comment by christiaanwesterbeek** [comment]
`getVisibleRange ` works on horizontal lists. I don't have time to elaborate much, so I'll throw some of a component that contains a horizontally scrolling list.

```javascript

listRef = React.createRef();
containerRef = React.createRef();

updateContainerInfo() {
    const [
        leftVisibleIndex,
        rightVisibleIndex,
    ] = this.listRef.current.getVisibleRange();
    ...
}

render() {
    return (
        ...
        <div
            className={classes.container}
            onScroll={this.updateContainerInfo}
            ref={this.containerRef}
        >
            <ReactList
                ref={this.listRef}
                itemRenderer={this.renderItem}
                itemSizeGetter={this.itemSizeGetter}
                length={data.length}
                type="variable"
                axis="x"
            />
        </div>
        ...
    );
}
```
