### ISSUE TITLE
Strict mode compatibility

### ISSUE THREAD

**Issue by byronanderson** [coderiety/react-list#227]
This library uses react's `componentWillReceiveProps` lifecycle, which has been deprecated in favor of `componentDidUpdate` and `getDerivedStateFromProps` for compatibility with async rendering (see [here](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html)).

I'm going to take a stab at updating the library to use new APIs, but I figured I'd open this issue first to see if anyone was already aware of this.

It is my understanding that libraries doing this update typically add `react-lifecycles-compat` as a dependency so as to support both the old versions of react and the new versions of react.  In this case, it is easy to implement the more restrictive `getDerivedStateFromProps` from `componentWillReceiveProps`, so I plan to implement the change in terms of `getDerivedStateFromProps` and use `react-lifecycles-compat` to support older react versions.

**Comment by christiaanwesterbeek** [comment]
@byronanderson Do you happen to be acquainted with the new Hooks API as well? :) I'm sure many would favor seeing hooks beings used in favor of the lifecycle methods (didMount, didUpdate, etc) that tend to look dated to my eyes already.

**Comment by byronanderson** [comment]
@christiaanwesterbeek I *am*, but I don't think that libraries can maintain compatibility across multiple versions of react while utilizing hooks.

Probably could target just newer versions of React for a major version release, but then again hooks don't change anything about how the components are consumed, so I would only think that that would be necessary in the context of trying to add features or squash bugs.

**Comment by byronanderson** [comment]
(closing this in favor of the PR #228)
