### ISSUE TITLE
Financing

### ISSUE THREAD

**Issue by brillout** [coderiety/react-list#240]
Hi :wave:,

I'm Romuald from the [Lsos](https://lsos.org/), an organization that develops financial solutions for open source projects, and we are currently doing outreach to projects we like.

One of our solutions is the [Lsos Commons](https://lsos.org/#lsos-commons) which I believe could fit; is that something ReactList would be interested in?

If not I'm sorry for having opened this ticket and I'll close it :).

**Comment by caseywebdev** [comment]
Hi @brillout, to be honest I feel like contributing open source projects like this are my way of paying for all of the other open source projects I use, so in that sense I'm all squared up 😉 

Additionally, I just don't have the time I feel like I'd need to dedicate to justify paid maintenance on this project. Thanks for the offer though and thanks for pushing OSS forward!

**Comment by brillout** [comment]
That makes sense :-) thanks for your reply and your wishes!
